name:                week6
version:             0.1.0.0
license:             BSD3      

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

dependencies:
- base >= 4.7 && < 5
- containers
- mtl
- pretty

library:
  source-dirs: src

executables:
 week6:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - week6
