name:                week3
version:             0.1.0.0
github:              "jackgilbride999/Topics-In-Functional/Weekly-Exercises/Week3"
license:             BSD3
author:              "Jack Gilbride"
copyright:           "(c) 2020 Jack Gilbride"

extra-source-files:
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/gdstrong/fib#readme>

dependencies:
- base >= 4.7 && < 5
- parallel


executables:
  week3: 
    main: week3.hs

# GThese options are global (because they are not indented into an 'executables' stanza)
source-dirs: src
ghc-options:
  - -threaded
  - -rtsopts

